import { Room } from './types';

export const initialRooms: Room[] = [
  {
    id: 'phong-khach',
    name: 'Phòng Khách',
    icon: '🛋️',
    color: 'from-blue-500 to-cyan-400',
    temperature: 28.5,
    humidity: 62,
    devices: [
      {
        id: 'ac-khach',
        type: 'ac',
        name: 'Điều Hoà',
        isOn: true,
        temperature: 25,
        mode: 'cool',
        fanSpeed: 'medium',
      },
      {
        id: 'tv-khach',
        type: 'tv',
        name: 'TV Samsung',
        isOn: true,
        volume: 30,
        channel: 7,
        input: 'hdmi1',
      },
      {
        id: 'fan-khach',
        type: 'fan',
        name: 'Quạt',
        isOn: false,
        speed: 'medium',
        oscillate: true,
      },
    ],
  },
  {
    id: 'phong-an',
    name: 'Phòng An',
    icon: '🛏️',
    color: 'from-violet-500 to-purple-400',
    temperature: 27.2,
    humidity: 58,
    devices: [
      {
        id: 'ac-an',
        type: 'ac',
        name: 'Điều Hoà',
        isOn: true,
        temperature: 26,
        mode: 'cool',
        fanSpeed: 'low',
      },
      {
        id: 'fan-an',
        type: 'fan',
        name: 'Quạt',
        isOn: true,
        speed: 'low',
        oscillate: false,
      },
    ],
  },
  {
    id: 'phong-min',
    name: 'Phòng Min',
    icon: '🎮',
    color: 'from-emerald-500 to-teal-400',
    temperature: 29.1,
    humidity: 65,
    devices: [
      {
        id: 'ac-min',
        type: 'ac',
        name: 'Điều Hoà',
        isOn: false,
        temperature: 24,
        mode: 'cool',
        fanSpeed: 'high',
      },
      {
        id: 'fan-min',
        type: 'fan',
        name: 'Quạt',
        isOn: true,
        speed: 'high',
        oscillate: true,
      },
    ],
  },
  {
    id: 'phong-lie',
    name: 'Phòng Lie',
    icon: '🌸',
    color: 'from-rose-500 to-pink-400',
    temperature: 30.3,
    humidity: 72,
    devices: [
      {
        id: 'ac-lie',
        type: 'ac',
        name: 'Điều Hoà',
        isOn: true,
        temperature: 23,
        mode: 'dry',
        fanSpeed: 'auto',
      },
      {
        id: 'dehumidifier-lie',
        type: 'dehumidifier',
        name: 'Máy Hút Ẩm',
        isOn: true,
        targetHumidity: 55,
        fanSpeed: 'medium',
      },
    ],
  },
];
